Repository Inventor77/Nutiveal-Nutrition-Data, pull requests merged in 2022-10, with the labels that each got.

#6 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#10 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#14 special note added
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#19 Added Edible Items from Nutrients.json
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#23 Moved Cod Liver oil to edibles.json
  data/edibles.json
  data/nutrients.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#26 Moved tuna to edible.json
  README.md
  data/edibles.json
  data/nutrients.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#27 Moved Chicker liver to edibles.json
  README.md
  data/edibles.json
  data/nutrients.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#29 Code refactoring
  CONTRIBUTING.md
  README.md
  data/Edibles.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#30 create a list of all edibles in nutrition.json
  Edibles In Nutrition.json File.md
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#31 Updated the readme file with guidelines
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#32 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#33 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#34 participating guidelines
  CONTRIBUTING.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#35 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#36 Add files via upload
  server.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#37 Add files via upload
  index.ipynb
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#38 App.js file for frontend
  App.js
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#40 index.ipynb
  App.js
  server.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#41 added soul bound token
  SBTtoken.sol
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#42 reveal functionality
  changelink.sol
Labels: hacktoberfest-accepted, hacktoberfest

#43 nft contract
  NFTcontract.sol
Labels: hacktoberfest-accepted, hacktoberfest

#44 auction contract
  A.sol
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#46 Updated CONTRIBUTING.md and corrected some typos
  CONTRIBUTING.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#48 Delete SBTtoken.sol
  SBTtoken.sol
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#49 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#50 Rename Edibles In to Nutrition.md
  Nutrition.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#51 moved nutrition.md
  data/Nutrition.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#52 Removed the useless list from readme.md
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#53 Delete NFTcontract.sol
  NFTcontract.sol
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#54 Delete changelink.sol
  changelink.sol
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#55 Delete index.ipynb
  index.ipynb
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#56 Update A.sol
  A.sol
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#57 Delete A.sol
  A.sol
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#58 Create Nutrients.md
  data/Nutrients.md
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#59 Update Nutrients.md
  data/Nutrients.md
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#60 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#61 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#62 update readme
  CONTRIBUTING.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#63 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#65 Added Nutrients
  utils/Ediables.py
  utils/Nutrients.py
  utils/__init__.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#66 Added ModifyChanges.py
  utils/ModifyChanges.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#67 Added RemoveChanges.py
  utils/Automate.py
  utils/RemoveChanges.py
  utils/__init__.py
Labels: hacktoberfest-accepted, hacktoberfest

#68 Delete Automate.py
  utils/Automate.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#69 Delete Ediables.py
  utils/Ediables.py
Labels: hacktoberfest-accepted, hacktoberfest

#70 Delete ModifyChanges.py
  utils/ModifyChanges.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#64 Added more edibles to nutrients.json
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#76 Update Edibles.md
  data/Edibles.md
Labels: hacktoberfest-accepted, hacktoberfest

#77 Update Edibles.md
  data/Edibles.md
Labels: hacktoberfest-accepted, hacktoberfest

#78 Update Edibles.md
  data/Edibles.md
Labels: hacktoberfest-accepted, hacktoberfest

#79 Update Edibles.md
  data/Edibles.md
Labels: hacktoberfest-accepted, hacktoberfest

#80 Update Edibles.md
  data/Edibles.md
Labels: hacktoberfest-accepted, hacktoberfest

#81 Update Edibles.md
  data/Edibles.md
Labels: hacktoberfest-accepted, hacktoberfest

#82 Update Nutrition.md
  data/Nutrition.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#83 Update Nutrition.md
  data/Nutrition.md
Labels: hacktoberfest-accepted, hacktoberfest

#84 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#85 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#86 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, hacktoberfest

#87 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, hacktoberfest

#88 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#89 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#90 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#91 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, hacktoberfest

#92 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#93 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#94 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#95 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#96 Added auto.py
  utils/auto.py
Labels: hacktoberfest-accepted, hacktoberfest
